### PR TITLE
Silence warnings in MSVC >= 1911 (VS2017)

### PR DESCRIPTION
**Pull request by AraHaan**
This is 1 commit na going to be list of possible commits to fix most (if not all) of MSVC's warnings.

### CODE REVIEW

**Comment by AraHaan** [comment]
@martinmoene I think this is ready for review by you. It works on my end though and suppresses the warnings correctly with all the warn options enabled that the built in code checking tool on VS2017 comes with.

**Comment by martinmoene** [comment]
Note to self: Consider using `[[gsl::suppress(bounds.1)]]` and the like via a macro, see [Using the C++ Core Guidelines checkers](https://docs.microsoft.com/en-us/visualstudio/code-quality/cpp-core-guidelines-warnings).

**Comment by martinmoene** [comment]
@AraHaan Thanks for your input. I've changed the code to suppress the warnings a little differently.

**Comment by AraHaan** [comment]
ah, alright

**Comment by martinmoene** [comment]
Suppression of C++ Core Guideline warnings are in [release 0.28.0](https://github.com/martinmoene/gsl-lite/releases/tag/v0.28.0).

**Comment by AraHaan** [comment]
thanks

**Pull request closed without merging**
