### PR TITLE
Add dedicated <gsl-lite/gsl-lite.hpp> header for v1

### PR DESCRIPTION
**Pull request by mbeutel**
As a ~first~ second step towards M-GSL compatibility (cf. #194, #222), this PR proposes the following change:

- Add new header file \<gsl-lite/gsl-lite.hpp\> which currently just forwards to the old header \<gsl/gsl-lite.hpp\>. It raises an error if `!(gsl_CONFIG_DEFAULTS_VERSION >= 1)`.

The idea is that libraries which want to use *gsl-lite* should do the following:

```c++
#include <gsl-lite/gsl-lite.hpp> // instead of <gsl/gsl-lite.hpp>

namespace foo {

namespace gsl = ::gsl_lite; // convenience alias

double mean(gsl::span<double const> elements)
{
    gsl_Expects(!elements.empty()); // instead of Expects()
    ...
}

} // namespace foo
```

Subsequently, version 1 of *gsl-lite* would then no longer define the namespace `gsl` in the \<gsl-lite/gsl-lite.hpp\> header. Library "foo" will then happily coexist with other code which uses either M-GSL or *gsl-lite* in "traditional mode" (or "GSL mode", or whatever we want to call it) by defining `gsl_FEATURE_GSL_MODE=1`, or by including the old header \<gsl/gsl-lite.hpp\> . (Cf. the comment below for more details; I'd appreciate thoughts and comments especially on this part.)

### CODE REVIEW

**Comment by mbeutel** [comment]
I'm still not quite sure about that new \<gsl-lite/gsl-lite.hpp\> header file.

I feel that \<gsl-lite/gsl-lite.hpp\> would be the appropriate header name for *gsl-lite* if we want *gsl-lite* to be more than just another GSL implementation, just as `gsl-lite::gsl-lite` would be the appropriate name for the CMake target. But I'm not sure if the benefits of making these changes outweigh the drawbacks.

If we do want to proceed with a dedicated `gsl_lite` namespace, I see two possibilities for version 1:

- Do not introduce a new header file. There is only \<gsl/gsl-lite.hpp\>, and it defines the namespace `gsl_lite` by default, and additionally the namespace `gsl` if `gsl_FEATURE_GSL_MODE` is defined:  
    
  ```c++
  // gsl/gsl-lite.hpp
  namespace gsl_lite { ... }
  namespace gsl_compat { using gsl_lite::span; ... }
  
  // Including the new header <gsl-lite/gsl-lite.hpp> enables "GSL mode" only if requested
  // by a feature macro.
  #if defined( gsl_FEATURE_GSL_MODE )
  namespace gsl = gsl_compat;
  # define Expects( x ) gsl_Expects( x )
  # define Ensures( x ) gsl_Ensures( x )
  #endif // defined( gsl_FEATURE_GSL_MODE )
  ```
    
  **Advantages:** less complexity and confusion, still trivially single-header  
    
  **Disadvantages:** breaks old code which expects everything to be in namespace `gsl`; the fix is trivial (define `gsl_FEATURE_GSL_MODE` in the build system), but it still is a breaking change, and we cannot really generate helpful diagnostics

- Introduce a new header file \<gsl-lite/gsl-lite.hpp\> in addition to \<gsl/gsl-lite.hpp\>.

  ```c++
  // gsl-lite/gsl-lite.hpp
  namespace gsl_lite { ... }
  namespace gsl_compat { using gsl_lite::span; ... }
  
  // Including the new header <gsl-lite/gsl-lite.hpp> enables "GSL mode" only if requested
  // by a feature macro.
  #if defined( gsl_FEATURE_GSL_MODE )
  namespace gsl = gsl_compat;
  # define Expects( x ) gsl_Expects( x )
  # define Ensures( x ) gsl_Ensures( x )
  #endif // defined( gsl_FEATURE_GSL_MODE )
  ```

  ```c++
  // gsl/gsl-lite.hpp
  #include <gsl-lite/gsl-lite.hpp>
  
  // Including the traditional header <gsl/gsl-lite.hpp> implicitly requests "GSL mode".
  //
  // If `gsl_FEATURE_GSL_MODE` is defined, the "GSL mode" definitions are already provided
  // by <gsl-lite/gsl_lite.hpp>, but they are idempotent, hence we can just state them again.
  namespace gsl = gsl_compat;
  # define Expects( x ) gsl_Expects( x )
  # define Ensures( x ) gsl_Ensures( x )
  ```
    
  **Advantages:** old code which references \<gsl/gsl-lite.hpp\> and expects a namespace `gsl` keeps working; \<gsl-lite/gsl-lite.hpp\> can still be used as single-header library (although then the `gsl_FEATURE_GSL_MODE` feature macro is required to enable the traditional mode)
    
  **Disadvantages:** more headers and more complexity; the distinction between  \<gsl/gsl-lite.hpp\> and  \<gsl-lite/gsl-lite.hpp\> is perhaps too subtle

@martinmoene and @petamas, I'd be grateful if you could take the time to comment on these thoughts. Of course this can wait until next year :)

**Comment by martinmoene** [comment]
@mbeutel noticed your request :)

**Comment by mbeutel** [comment]
The new `gsl_lite` namespace, probably less controversial, is now tracked separately in #222.

**Comment by mbeutel** [comment]
I've been thinking about this for a while, and I believe that the new header file is the superior choice. Those who need a single-header GSL implementation will then need to define a build configuration macro like `gsl_FEATURE_GSL_MODE`, which seems bearable.

**Comment by martinmoene** [comment]
@mbeutel sorry for slacking, couldn't make up my mind, hadn't come further than the split you made to enable different time paths. Support the choice you made, whichever it would have been. 

Like to mention I'm very happy and grateful for the professional approach and the direction you take *gsl lite*. Thanks very much!

**Comment by mbeutel** [comment]
No worries! Thank you for your support :)

**Pull request merged**
