### PR TITLE
Add CI for CUDA

### PR DESCRIPTION
**Pull request by mbeutel**
This PR adds some CI for CUDA and fixes the warnings shown by NVCC when compiling *gsl-lite*.

Note that CI isn't there yet; it will show up in a subsequent commit.

### CODE REVIEW

**Comment by martinmoene** [comment]
@mbeutel  uhm sorry, inadvertently clicked on "ready for review"

**Comment by mbeutel** [comment]
And now I inadvertently closed it because no changes were left after rebasing. As you say, so much to learn :)

**Comment by mbeutel** [comment]
This PR now contains a CI definition file for Azure Pipelines in addition to the Travis and AppVeyor pipelines. @martinmoene, could you please give me a hand and install the [Azure Pipelines app](https://github.com/apps/azure-pipelines/installations/new) for this repository?

**Comment by martinmoene** [comment]
@mbeutel , think I [installed the Azure Pipelines app](https://github.com/martinmoene/gsl-lite/settings/installations) for *gsl lite* (only :)

**Pull request merged**
